### ISSUE TITLE
Exécuter les tests Behat dans le système d'intégration continu

### ISSUE THREAD

**Issue by lenybernard** [AppVentus/Academie#2]
Essayer de les faire fonctionner dans Jenkins, sinon il faudra essayer avec Bamboo ou Travis (si possible avec Bitbucket)

**Comment by ghost** [comment]
Travis n'est pas disponible sur Bitbucket

Le 1 août 2013 15:56, Leny BERNARD notifications@github.com a écrit :

> Essayer de les faire fonctionner dans Jenkins, sinon il faudra essayer
> avec Bamboo ou Travis (si possible avec Bitbucket)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/AppVentus/Academie/issues/2
> .

## 

_Pierre JOLLY_
_Développeur Symfony chez AppVentus SAS_
*
*
22 rue crébillon, 44000 Nantes
Tel : 06.66.77.75.20 | Email : pierre@appventus.com
AppVentus http://appventus.com - Sites web et applications

**Comment by lenybernard** [comment]
Article écrit sur le blog par Paul : http://appventus.com/blog/tests-behat-avec-bamboo-ci-atlassian
