### ISSUE TITLE
[Convention] Doctrine repository

### ISSUE THREAD

**Issue by ghost** [AppVentus/Academie#4]
Il serait bon de définir une convention de nommage pour faire la différence entre les fonctions retournant une requête exécuté et celle retournant un objet QueryBuilder.

Le mieux serait surement d'écrire deux fonctions, une get() qui retourne le QueryBuilder, et une find() qui exécute la fonction get() précédente.

``` php
<?php

namespace My\FooBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * FooRepository
 */
class FooRepository extends EntityRepository
{
    /**
     * Return Foo by name.
     *
     * @param string $name
     * @return QueryBuilder $qb
     */
    public function getByName($name)
    {
        $qb->where('mission:name = :mission_name')
            ->setParameter('mission_name', $name);

        return $qb;
    }

    /**
     * Execute function getByName()
     *
     * @see getByName()
     * @return array
     */
    public function findByName($name)
    {
        return $this->getByName($name)
            ->getQuery()
            ->getResult();
    }
}
```

**Comment by juliensnz** [comment]
Ouep, il serait bon de faire une différence. De cette façon, rendu dans un contrôleur on pourra savoir directement si on obtient un qb ou une collection.

Symfony2 utilise find pour retourner des résultats directement alors pourquoi pas utiliser get pour le querybuilder.

**Comment by lenybernard** [comment]
Yes, je pense que c'est une très bonne idée. :+1:
