### ISSUE TITLE
[Good practice] Service

### ISSUE THREAD

**Issue by ghost** [AppVentus/Academie#5]
Dans les service je trouve que c'est une bonne pratique de rappeler l'id du service dans le docblock

Exemple :

``` php
<?php
namespace My\FooBundle\Service;

/**
 * FooService
 *
 * service id : my_app.service.foo
 */
class FooService
{
    // Service here
}
```

Lorsque l'on à de nombreux services, cela permet de retrouver rapidement et facilement l'id à utiliser.

**Comment by paulandrieux** [comment]
+1

**Comment by ghost** [comment]
Pendant que j'y pense il en va de même pour les formulaires :)
